spring.application.name=queboleta

# Puerto
server.port=8080

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=MiClaveJWTUltraSeguraParaQueBoleta2026ConMasDe256Bits
app.jwt.expiration=86400000

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/queboleta_db
spring.datasource.username=root
spring.datasource.password=juan2010